services/urls.py
from django.urls import path
from services import views
urlpatterns = [
    path('', views.index_page),
    path('our-histoy/', views.our_history),
    path('at-glance/', views.at_a_glance),
    path('about-school/', views.about_school),
    path('all-member/', views.all_member),
    path('about-us/', views.about_us),
    path('teacher-info/', views.teacher_info),
    path('student-info/', views.student_info),
    path('work-gallary/', views.work_gallary),
    # path('our-history/', views.our_history),
    # path('institute-message/', views.institute_message),
    path('chairman-message/', views.chairman_message),
    path('principal-message/', views.principal_message),
    path('president-message/', views.president_message),
    path('generalsecretary-message/', views.general_secretary),

    # path('institute/teachers/', views.teacher_info),
    path('associations/committee/', views.committee_info),
    # path('institute/at-glance/', views.at_a_glance),
    # path('institute/why-study/', views.why_loginstudy_here),
    # path('institute/facility/', views.institute_facility),
    # path('all-notices/', views.all_notices),
    path('gallery/photo-gallery/', views.photo_gallery),
    path('gallery/video-gallery/', views.video_gallery),
    path('previous-events/', views.previous_events),
    path('notice-event/', views.all_notices),
    path('notice/<int:id>/view/', views.view_notices),
    path('user-registation/', views.user_registation),
    path('login/', views.login),
    # path('all-events/', views.all_events),
    # path('events/<int:id>/view/', views.view_events),
    # path('institute/eiin-number/', views.eiin_number),
    # path('institute/library/', views.library_page),
    # path('institute/hostel/', views.hostel_page),
    # path('institute/lab/', views.lab_page),
    # path('institute/idcard/', views.idcard_page),
    # path('institute/quran-class/', views.quran_class),
    # path('institute/bncc/', views.bncc_page),
    # path('institute/scout/', views.scout_page),
    # path('admission/', views.admission_form),
    # path('exam-regulations/', views.exam_regulations),
    # path('admission-suspension/', views.admission_suspension),
    # path('admission-information/', views.admission_information),
    # path('job-vacancy/', views.job_vacancy),
    # path('contact-us/', views.contact_us),
    # path('result-history/', views.result_history),
    # path('logout/', views.admin_logout),
    # path('search-result/', views.search_result),

    # # Dashboard
    # path('dashboard/', views.dashboard),
    # path('student-registration/', views.student_reg),
    # path('quick-admission/', views.quick_admission),
    # path('quick-admission-list/', views.quick_admission_list),
    # path('student-list/', views.student_list),
    # path('remove-student/<int:id>/', views.remove_student),
    # path('student-photos-list/', views.student_photos_list),
    # path('parents-list/', views.parents_list),
    # path('parents-photos-list/', views.parents_photos_list),
    # path('guardian-list/', views.guardian_list),
    # path('guardian-photo-list/', views.guardian_photos_list),
    # path('scholarship-student-list/', views.scholarship_student_list),
    # path('inactive-student-list/', views.inactive_student_list),
    # path('employee-registration/', views.employee_reg),
    # path('employee-list/', views.employee_list),
    # path('remove-employee/<int:id>', views.remove_employee),
    # path('add-class-teacher/', views.add_class_teacher),
    # path('teacher-list/', views.teacher_list),
    # path('class-teacher-assign-delete/<int:id>/', views.delete_teacher),
    # path('student-exam-marks-entry/', views.student_exam_mark),
    # path('mark-distribution/', views.mark_distribution),
    # path('mark-distribution-list/', views.mark_distribution_list),
    # path('remove-mark-distribution/<int:id>', views.delete_mark_distribution),
    
    # # Export in Excel
    # path('export-student-sheet/', views.export_student_list),

    # # report 
    # path('class-wise-report/', views.class_wise_report),

]

sogsnaa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
import email
import imp
import os
from tabnanny import verbose
from unicodedata import name
from django.db import models
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextField    
from datetime import datetime
from django.utils import timezone

from services.views import previous_events


class HomeContent(models.Model):
    content_type = (
        ('1', 'Our History'),
        ('2', 'About Us'),
        ('3', 'About School'),
        ('4', 'At a Glance'),
    )
    content_for  = models.CharField(max_length=1, choices = content_type)
    details      = RichTextField(blank=True)
    pub_date     = models.DateField(auto_now_add = True)
    status       = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.content_for)
    
    class Meta:
        verbose_name = 'Home Content'
        verbose_name_plural = 'Home Contents'

class Batch(models.Model):
    year          = models.CharField(max_length=20, unique=True)
    insert_date   = models.DateTimeField(auto_now_add=True)
    status        = models.BooleanField(default=True) 
    
    def __str__(self):
        return str(self.year)

    class Meta:
        verbose_name = "Batch"
        verbose_name_plural = "Batch" 

class CommitteeInfo(models.Model):
    member_name        = models.CharField(max_length=100, blank=True)
    email              = models.EmailField(max_length=100, blank=True)
    phone              = models.CharField(max_length=100, blank=True)
    designation        = models.CharField(max_length=50, blank=True)
    qualification      = models.CharField(max_length=300, blank=True)
    date_of_birth      = models.DateField(auto_now_add = False)
    genders = (
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Others'),
    )
    gender             = models.CharField(max_length=1, choices = genders)
    present_address    = models.CharField(max_length=500,blank=True)
    permament_address  = models.CharField(max_length=500,blank=True)
    batch              = models.ForeignKey(Batch, on_delete=models.CASCADE)
    member_image       = models.FileField(upload_to='member_image',blank=True)
    order              = models.IntegerField(default=0)
    facebook           = models.CharField(max_length=200,blank=True)
    twitter            = models.CharField(max_length=200,blank=True)
    status             = models.BooleanField(default=True)
    
    def __str__(self):
        return self.member_name

    class Meta:
        verbose_name = 'Committee Information'
        verbose_name_plural = 'Committee Informations' 

class AllInfo(models.Model):
    info_type = (
        ('1', 'teacher info'),
        ('2', 'student info'),
    )
    info_for            = models.CharField(max_length=1, choices = info_type)
    name                = models.CharField(max_length=100, blank=True)
    designation         = models.CharField(max_length=100, blank=True)
    qualifications      = models.CharField(max_length=150, blank=True)
    info_image          = models.FileField(upload_to='Info_image',blank=True)
    email               = models.EmailField(max_length=100, blank = True)
    facebook            = models.CharField(max_length=200,blank=True)
    twitter             = models.CharField(max_length=200,blank=True)
    order               = models.IntegerField(default=0)
    status              = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'teacher students info'
        verbose_name_plural = 'teacher students infos'

class WorkGallery(models.Model):
    work_title          = models.CharField(max_length=100, blank=True)
    work_image          = models.FileField(upload_to='work_image',blank=True)
    order              = models.IntegerField(default=0)
    status              = models.BooleanField(default=True)

    def __str__(self):
        return self.work_title

    class Meta:
        verbose_name = 'work gallary'
        verbose_name_plural = 'add work gallary'

        
class SliderInfo(models.Model):
    slider_title   = models.CharField(max_length=100, blank=True)
    details        = models.TextField(max_length=5000, blank=True)
    images         = models.ImageField(upload_to='slider')
    slider_order   = models.IntegerField(default=0)
    status         = models.BooleanField(default=True)
    upload_date    = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.slider_title

    class Meta:
        verbose_name = 'Slider Image'
        verbose_name_plural = 'Slider Images' 
class GalleryInfo(models.Model):
    type = (
        ('1',  'Video Gallery'),
        ('2',  'Photo Gallery'),
    )
    gallery_type  = models.CharField(max_length=3, choices=type)
    image_choice = (
        ('1',  'Hostel'),
        ('2',  'Library'),
        ('3',  'Lab'),
        ('5',  'ID Card'),
    )
    gallery_for     = models.CharField(max_length=3, choices=image_choice, blank=True)
    gallery_title   = models.CharField(max_length=100, blank=True)
    gallery_images  = models.ImageField(upload_to='gallery', blank=True)
    gallery_link    = models.CharField(max_length=250)
    gallery_order   = models.IntegerField()
    status          = models.BooleanField(default=True)
    upload_date     = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.gallery_title

    class Meta:
        verbose_name = 'Gallery Info'
        verbose_name_plural = 'Add Gallery'

class PreviousEvents(models.Model):
    previous_title  = models.CharField(max_length=250, blank = True)
    video_url       = models.CharField(max_length=250)
    gallery_order   = models.IntegerField()
    status          = models.BooleanField(default=True)
    upload_date     = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.previous_title

    class Meta:
        verbose_name = 'Previous Event'
        verbose_name_plural = 'Previous Event'

class SchoolProfile(models.Model):
    school_name       = models.CharField(max_length=160)
    slugan            = models.CharField(max_length=100, blank=True)
    email             = models.EmailField(max_length=70,blank=True)
    phone             = models.CharField(max_length=20)
    mobile            = models.CharField(max_length=15)
    address           = models.CharField(max_length=200)
    web_address       = models.CharField(max_length=200,blank=True)
    logo              = models.ImageField(upload_to='company_info')
    facebook_id       = models.CharField(max_length=200,blank=True)
    twitter_id        = models.CharField(max_length=200,blank=True)
    google_id         = models.CharField(max_length=200,blank=True)
    youtube_id        = models.CharField(max_length=200,blank=True)
    linkedin_id       = models.CharField(max_length=200,blank=True)
    copyright_name    = models.CharField(max_length=200,blank=True)
    status            = models.BooleanField(default=True)
    
    def __str__(self):
        return self.school_name

    class Meta:
        verbose_name = 'School Profile'
        verbose_name_plural = 'School Profile'


class MessageInfo(models.Model):
    message_type = (
        ('1',  'Welcome Message'),
        ('2',  'Chairman Message'),
        ('3',  'Principal Message'), 
        ('4',  'President Message'), 
        ('5',  'General Secretary Message'), 
    )
    message_for     = models.CharField(max_length=1, choices=message_type)
    # message_title   = models.CharField(max_length=100, blank=True)
    details         = RichTextField(blank=True)
    persion_images  = models.ImageField(upload_to='images/institute', blank=True)
    status          = models.BooleanField(default=True)
    upload_date     = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.message_for)

    class Meta:
        verbose_name = 'Academic Message'
        verbose_name_plural = 'Academic Message'

class NoticeAndEvent(models.Model):
    type = (
        ('1',  'Notice'),
        ('2',  'Events'),
    )
    notice_or_event  = models.CharField(max_length=3, choices=type)
    title            = models.CharField(max_length=100, blank=True)
    details          = RichTextField(blank=True)
    upload_images    = models.ImageField(upload_to='notice_event_image', blank=True)
    notice_file      = models.FileField(upload_to='notice_file', blank=True)
    upload_date      = models.DateField(auto_now_add=True)
    status           = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Notice Event'
        verbose_name_plural = 'Add Notice and Event'

class ImportantLink(models.Model):
    link_name      = models.CharField(max_length=100)
    link_url       = models.CharField(max_length=60, blank=True)
    order          = models.IntegerField()
    status         = models.BooleanField(default=True)

    def __str__(self):
        return self.link_name

    class Meta:
        verbose_name = 'Important Link'
        verbose_name_plural = 'Add Important Link'

class Contact(models.Model):
    name             = models.CharField(max_length = 100)
    email            = models.EmailField(max_length = 100,blank = True)
    subject          = models.CharField(max_length = 150)
    phone            = models.CharField(max_length = 20)
    message          = RichTextField()
    message_date     = models.DateTimeField(auto_now_add=True)
    status           = models.BooleanField(default = True)

    def __str__(self):
        return self.name   

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

class Session(models.Model):
    session_name  = models.IntegerField(default=0, unique=True)
    insert_date   = models.DateTimeField(auto_now_add=True)
    status        = models.BooleanField(default=1)

    def __str__(self):
        return str(self.year)

    class Meta:

services/templates/services/all_member.html
{% extends 'services/base.html' %}
{% block title %} Photo Gallery  {% endblock %}
{% load static %}
{% block content %}
<div class="single_page_bg">
    <!-- Section: inner-header -->
     <section class="inner-header divider layer-overlay overlay-theme-colored-7"  style="background-image: url(/static/school/images/background.png);">
        <div class="container">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-md-6">
                        <h1 class="text-theme-colored2 font-36">All Member</h1>
                        <ol class="breadcrumb text-left mt-10 white">
                            <li><a href="/">Home</a></li>
                            <li class="active">All Member</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
<div class="container">
    <div class="row">
     {% for data in all_member %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="our-team">
            <div class="picture">
                <img style="width: 130px;height: 130px;" class="img-fluid" src="/static/services/media/{{ data.member_image }}">
            </div>
            <div class="team-content">
                <h3 class="name">{{ data.name }}</h3>
                <h4 class="title">{{data.qualification}}</h4>
            </div>
            <ul class="social">
                <li><a href="#" class="fa fa-facebook" aria-hidden="true"></a></li>
                <li><a href="#" class="fa fa-twitter" aria-hidden="true"></a></li>
                <li><a href="#" class="fa fa-google-plus" aria-hidden="true"></a></li>
                <li><a href="#" class="fa fa-linkedin" aria-hidden="true"></a></li>
            </ul>
            </div>
        </div>
     {% endfor %}     
    </div>
  </div>



{% comment %} <div class="single_page_bg">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="teacher_title"> Photo Gallery</h1>
            </div>
        </div>
        <div class="row">
            {% for data in gallery_list %}
            <div class="col-sm-4">
               <div class="photo_gallery">
                   <img src="/static/school/media/{{ data.gallery_images }}" alt="">
                   <h4>{{ data.gallery_title }}</h4>
               </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div> {% endcomment %}

{% endblock %} 

services/templates/services/api.html
{% extends 'school/base.html' %}
{% block title %} API {% endblock %}
{% load static %}
{% block content %}
<div class="single_page_bg">
    {% for data in api %}
        <p>{{data.userId }}</p>
        <p>{{data.id }}</p>
        <p>{{data.title }}</p>
        <p>{{data.body }}</p>
    {% endfor %}
</div>
{% endblock %}

services/templates/services/eiin_number.html
{% extends 'services/base.html' %}
{% block title %} Management Committee  {% endblock %}
{% load static %}
{% block content %}

<div class="single_page_bg">
    <!-- Section: inner-header -->
    <section class="inner-header divider layer-overlay overlay-theme-colored-7"  style="background-image: url(/static/school/images/background.png);">
        <div class="container">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-md-6">
                        <h1 class="text-theme-colored2 font-36">EIIN Number</h1>
                        <ol class="breadcrumb text-left mt-10 white">
                            <li><a href="/">Home</a></li>
                            <li class="active">EIIN Number</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Section: About -->
    <section>
        <div class="container">
            <div class="row">
                <div class="book_area table-responsive">
                    <table class="table table-bordered table-hover">
                        <tbody>
                            <tr class="eiin">
                                <th>নাম </th>
                                <th> EIIN নাম্বার </th>
                            </tr>
                            <tr>
                                <td> ব্রাইট ষ্টার হাই স্কুল, ঢাকা </td>
                                <td> 132140 </td>
                            </tr>
                            <tr>
                                <td> ব্রাইট ষ্টার হাই স্কুল, চট্টগ্রাম  </td>
                                <td> 137640 </td>
                            </tr>
                            <tr>
                                <td> কিংস কলেজ </td>
                                <td> 131218 </td>
                            </tr>
                            <tr>
                                <td> উইনসাম কলেজ </td>
                                <td> 134446 </td>
                            </tr>
                            <tr>
                                <td> মেট্রোপলিটন কলেজ</td>
                                <td> 134265 </td>
                            </tr>
                            <tr>
                                <td> নর্থ সিটি কলেজ </td>
                                <td> 137099 </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %} 

services/templates/services/idcard_page.html
{% extends 'services/base.html' %}
{% block title %} ID Card {% endblock %}
{% load static %}
{% block content %}
<style>
    #owl-demo .item{
        margin: 3px;
        }
        #owl-demo .item img{
        display: block;
        width: 100%;
        height: auto;
        }
</style>
<div class="single_page_bg">
    <div class="container">
        <div class="row">
            <div class="facility_page_content">
                <img src="/static/school/media/{{ idcard.facility_images }}" alt=""> 
                <h3>{{ idcard.facility_title }}</h3>
                <hr>
                {{ idcard.details|safe }}
            </div>
           {% if hostel_image %}
            <div class="facility_gallery">
                <h3>ID Card Gallery</h3>
                <div id="owl-demo" class="owl-carousel owl-theme">
                    {% for data in idcard_image %}
                    <div class="item gallery_images_for_facility"> 
                        <img src="/static/school/media/{{ data.gallery_images }}" alt="{{ data.gallery_title }}"/> 
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %} 

services/templates/services/index.html
{% extends 'services/base.html' %}
{% load static %}
{% block content %}
    <div class="banner_slider">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
            {% for slide in banner_list %}   
                {% if forloop.first %}
                <div class="carousel-item active">
                    <img class="d-block w-100" src="/static/services/media/{{ slide.images }}" alt="{{ slide.slider_title }}" height="360">
                </div>
                {% else %}
                <div class="carousel-item">
                    <img class="d-block w-100" src="/static/services/media/{{ slide.images }}" alt="{{ slide.slider_title }}" height="360">
                </div>
                {% endif %}
            {% endfor %}
              
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    {% comment %} <div class="welcome_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="corner_slider">
                        <h2>Corner Message</h2>
                        <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for slide in corner_list %}   
                                    {% if forloop.first %}
                                    <div class="carousel-item active">
                                        <img class="d-block w-100" src="/static/services/media/{{ slide.images }}" alt="{{ slide.slider_title }}" height="300">
                                        <center style="background:#eee;padding:5px;">
                                            <h4>{{ slide.slider_title }}</h4>
                                            <h5>{{ services_info.services_name }}</h5>
                                        </center>
                                    </div>
                                    {% else %}
                                    <div class="carousel-item">
                                        <img class="d-block w-100" src="/static/services/media/{{ slide.images }}" alt="{{ slide.slider_title }}" height="300">
                                        <center style="background:#eee;padding:5px;">
                                            <h4>{{ slide.slider_title }}</h4>
                                            <h5>{{ services_info.services_name }}</h5>
                                        </center>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="welcome_message">
                        <h2>{{ welcome_message.get_message_for_display }}</h2>
                            {{ welcome_message.details|safe|slice:"650" }}</br>
                        <a href="/our-history/" class="btn btn-danger">Read more...</a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="notice_board">
                        <h2>Notice Board</h2>
                        <ul>
                            {% for data in noties_list %}
                            <li><a href="/notice/{{ data.pk }}/view/">
                                <div class="date_pull">
                                    <h4>{{ data.upload_date|date:"d" }}</h4>
                                    <h3>{{ data.upload_date|date:"N" }}</h3>
                                </div>
                                <div class="details_pull">
                                    <h3>{{ data.title }}</h3>
                                    <p>{{ data.upload_date }}</p>
                                </div>
                            </a></li>
                         {% endfor %}
                            
                            <a href="/all-notices" class="btn btn-danger"> All Notices</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="activities_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="choose_title">Why Choose Us</h3>
                </div>
            </div>
            <div class="row">
                {% for data in activities_list %}
                <div class="col-sm-3 active_item">
                    <div class="activities_item">
                       <h5><i class="{{ data.icon }}"></i></h5>
                        <h3>{{ data.activites_name }}</h3>
                        {{ data.details|safe|slice:"80" }}
                        <h6><a href="" class="btn btn-danger">Read more...</a></h6>
                    </div>
                </div>
                {% endfor %}
               
            </div>
        </div>
    </div>

    <div class="event_and_usefull_link">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="notice_board">
                        <h2>News & Event</h2>
                        <ul>
                            {% for data in event_list %}
                                <li><a href="/events/{{ data.pk }}/view/">
                                    <div class="date_pull">
                                        <h4>{{ data.upload_date|date:"d" }}</h4>
                                        <h3>{{ data.upload_date|date:"N" }}</h3>
                                    </div>
                                    <div class="details_pull">
                                        <h3>{{ data.title }}</h3>
                                        <p>{{ data.upload_date }}</p>
                                    </div>
                                </a></li>
                            {% endfor %}
                            
                            <a href="/all-events" class="btn btn-danger"> All Events</a>
                        </ul>
                    </div>
                </div>
                
                <div class="col-sm-4">
                    <div class="following_us">
                        <h2>Following Us</h2>
                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FUttaraUniversity&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=869161710111738" width="340" height="300" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="userfull_link">
                        <h2>Important Link</h2>
                        <ul>
                            {% for data in linklist %}
                            <li><a href="{{ data.link_url }}" target="_blank"><i class="fa fa-link"></i> {{ data.link_name }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> {% endcomment %}

    {% endblock %}    

services/templates/services/institute_facility.html
{% extends 'services/base.html' %}
{% block title %} Institute Facilities {% endblock %}
{% load static %}
{% block content %}

<div class="single_page_bg">
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="choose_title">Our Facilities</h3>
                </div>
            </div>
            <div class="row">
                {% for data in activities_list %}
                <div class="col-sm-3 active_item">
                    <div class="activities_item">
                        <h5><i class="{{ data.icon }}"></i></h5>
                        <h3>{{ data.activites_name }}</h3>
                        {{ data.details|safe|slice:"80" }}
                        <h6><a href="" class="btn btn-danger">Read more...</a></h6>
                    </div>
                </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
</div>

{% endblock %} 